export const PATIENT_COUNT_PER_DOCTOR = [
  {
    doctor_id: 1011,
    doctor_name: "Dr. PL Das",
    doctor_email: "pldas@hmhospital.com",
    doctor_phone: 9878900998,
    week_one: 120,
    week_two: 80,
    week_three: 20,
    week_four: 300,
  },
  {
    doctor_id: 1012,
    doctor_name: "Dr. Kamal Boro",
    doctor_email: "kamalboro@hmhospital.com",
    doctor_phone: 9878900111,
    week_one: 20,
    week_two: 50,
    week_three: 120,
    week_four: 70,
  },
  {
    doctor_id: 1013,
    doctor_name: "Dr. Kabrambam Lenglung",
    doctor_email: "kblenglung@hmhospital.com",
    doctor_phone: 9878911111,
    week_one: 60,
    week_two: 230,
    week_three: 100,
    week_four: 89,
  },
];

export const NIVO_BARCHART_DATA = [
  {
    country: "AD",
    "hot dog": 70,
    "hot dogColor": "hsl(335, 70%, 50%)",
    burger: 104,
    burgerColor: "hsl(102, 70%, 50%)",
    sandwich: 1,
    sandwichColor: "hsl(265, 70%, 50%)",
    kebab: 12,
    kebabColor: "hsl(96, 70%, 50%)",
    fries: 151,
    friesColor: "hsl(194, 70%, 50%)",
    donut: 180,
    donutColor: "hsl(294, 70%, 50%)",
  },
  {
    country: "AE",
    "hot dog": 180,
    "hot dogColor": "hsl(335, 70%, 50%)",
    burger: 198,
    burgerColor: "hsl(59, 70%, 50%)",
    sandwich: 73,
    sandwichColor: "hsl(242, 70%, 50%)",
    kebab: 44,
    kebabColor: "hsl(252, 70%, 50%)",
    fries: 57,
    friesColor: "hsl(144, 70%, 50%)",
    donut: 59,
    donutColor: "hsl(193, 70%, 50%)",
  },
  {
    country: "AF",
    "hot dog": 99,
    "hot dogColor": "hsl(254, 70%, 50%)",
    burger: 181,
    burgerColor: "hsl(320, 70%, 50%)",
    sandwich: 157,
    sandwichColor: "hsl(261, 70%, 50%)",
    kebab: 78,
    kebabColor: "hsl(41, 70%, 50%)",
    fries: 168,
    friesColor: "hsl(284, 70%, 50%)",
    donut: 13,
    donutColor: "hsl(241, 70%, 50%)",
  },
  {
    country: "AG",
    "hot dog": 28,
    "hot dogColor": "hsl(52, 70%, 50%)",
    burger: 33,
    burgerColor: "hsl(22, 70%, 50%)",
    sandwich: 167,
    sandwichColor: "hsl(186, 70%, 50%)",
    kebab: 136,
    kebabColor: "hsl(116, 70%, 50%)",
    fries: 158,
    friesColor: "hsl(345, 70%, 50%)",
    donut: 74,
    donutColor: "hsl(344, 70%, 50%)",
  },
  {
    country: "AI",
    "hot dog": 23,
    "hot dogColor": "hsl(41, 70%, 50%)",
    burger: 81,
    burgerColor: "hsl(22, 70%, 50%)",
    sandwich: 105,
    sandwichColor: "hsl(21, 70%, 50%)",
    kebab: 42,
    kebabColor: "hsl(286, 70%, 50%)",
    fries: 26,
    friesColor: "hsl(164, 70%, 50%)",
    donut: 64,
    donutColor: "hsl(123, 70%, 50%)",
  },
  {
    country: "AL",
    "hot dog": 42,
    "hot dogColor": "hsl(75, 70%, 50%)",
    burger: 85,
    burgerColor: "hsl(150, 70%, 50%)",
    sandwich: 193,
    sandwichColor: "hsl(189, 70%, 50%)",
    kebab: 90,
    kebabColor: "hsl(350, 70%, 50%)",
    fries: 21,
    friesColor: "hsl(259, 70%, 50%)",
    donut: 144,
    donutColor: "hsl(216, 70%, 50%)",
  },
  {
    country: "AM",
    "hot dog": 39,
    "hot dogColor": "hsl(177, 70%, 50%)",
    burger: 54,
    burgerColor: "hsl(206, 70%, 50%)",
    sandwich: 198,
    sandwichColor: "hsl(129, 70%, 50%)",
    kebab: 78,
    kebabColor: "hsl(126, 70%, 50%)",
    fries: 101,
    friesColor: "hsl(15, 70%, 50%)",
    donut: 147,
    donutColor: "hsl(216, 70%, 50%)",
  },
];

// export const PATIENT_COUNT_PER_DOCTOR = [
//   {
//     id: 0,
//     doctor_name: "Dr. PL Das",
//     doctor_email: "pldas@hmhospital.com",
//     doctor_phone: 9878900998,
//     week_one: 120,
//     week_two: 80,
//     week_three: 20,
//     week_four: 300,
//     // patient_count: {
//     // [
//     //   {
//     //     patient_id: "120",
//     //     patient_name: "Kamala Singh",
//     //     patient_gender: "female",
//     //     patient_age: 73,
//     //     patient_phone: 8883392920,
//     //     patient_email: "kamalasingh2233@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "231",
//     //     patient_name: "Kenny Deori",
//     //     patient_gender: "male",
//     //     patient_age: 70,
//     //     patient_phone: 1192003948,
//     //     patient_email: "kennydeori22@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "120",
//     //     patient_name: "Kamala Singh",
//     //     patient_gender: "female",
//     //     patient_age: 73,
//     //     patient_phone: 8883392920,
//     //     patient_email: "kamalasingh2233@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "231",
//     //     patient_name: "Kenny Deori",
//     //     patient_gender: "male",
//     //     patient_age: 70,
//     //     patient_phone: 1192003948,
//     //     patient_email: "kennydeori22@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "120",
//     //     patient_name: "Kamala Singh",
//     //     patient_gender: "female",
//     //     patient_age: 73,
//     //     patient_phone: 8883392920,
//     //     patient_email: "kamalasingh2233@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "231",
//     //     patient_name: "Kenny Deori",
//     //     patient_gender: "male",
//     //     patient_age: 70,
//     //     patient_phone: 1192003948,
//     //     patient_email: "kennydeori22@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "120",
//     //     patient_name: "Kamala Singh",
//     //     patient_gender: "female",
//     //     patient_age: 73,
//     //     patient_phone: 8883392920,
//     //     patient_email: "kamalasingh2233@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "231",
//     //     patient_name: "Kenny Deori",
//     //     patient_gender: "male",
//     //     patient_age: 70,
//     //     patient_phone: 1192003948,
//     //     patient_email: "kennydeori22@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     // ],
//     // [
//     //   {
//     //     patient_id: "10",
//     //     patient_name: "Bijoy madhav",
//     //     patient_gender: "male",
//     //     patient_age: 64,
//     //     patient_phone: 888339289,
//     //     patient_email: "bmadhav@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "200",
//     //     patient_name: "Shalini Singh",
//     //     patient_gender: "female",
//     //     patient_age: 79,
//     //     patient_phone: 1192008908,
//     //     patient_email: "shalinis11@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "10",
//     //     patient_name: "Bijoy madhav",
//     //     patient_gender: "male",
//     //     patient_age: 64,
//     //     patient_phone: 888339289,
//     //     patient_email: "bmadhav@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "200",
//     //     patient_name: "Shalini Singh",
//     //     patient_gender: "female",
//     //     patient_age: 79,
//     //     patient_phone: 1192008908,
//     //     patient_email: "shalinis11@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     // ],
//     //  [
//     //   {
//     //     patient_id: "1011",
//     //     patient_name: "Geeta Biswas",
//     //     patient_gender: "female",
//     //     patient_age: 60,
//     //     patient_phone: 888339111,
//     //     patient_email: "gbiswas@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "2011",
//     //     patient_name: "Gangadhar Bidyadhar",
//     //     patient_gender: "male",
//     //     patient_age: 81,
//     //     patient_phone: 1192008111,
//     //     patient_email: "shaktiman90s@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     // ],
//     // [
//     //   {
//     //     patient_id: "1101",
//     //     patient_name: "James Bond",
//     //     patient_gender: "male",
//     //     patient_age: 66,
//     //     patient_phone: 888331021,
//     //     patient_email: "bondo@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "2059",
//     //     patient_name: "Anya Frodger",
//     //     patient_gender: "female",
//     //     patient_age: 78,
//     //     patient_phone: 1192777111,
//     //     patient_email: "anyaf@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "1101",
//     //     patient_name: "James Bond",
//     //     patient_gender: "male",
//     //     patient_age: 66,
//     //     patient_phone: 888331021,
//     //     patient_email: "bondo@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "2059",
//     //     patient_name: "Anya Frodger",
//     //     patient_gender: "female",
//     //     patient_age: 78,
//     //     patient_phone: 1192777111,
//     //     patient_email: "anyaf@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     // ],
//     // },
//   },
//   {
//     id: 1,
//     doctor_name: "Dr. Kamal Boro",
//     doctor_email: "kamalboro@hmhospital.com",
//     doctor_phone: 9878900111,
//     week_one: 20,
//     week_two: 50,
//     week_three: 120,
//     week_four: 70,
//     // patient_count: {
//     //  [
//     //   {
//     //     patient_id: "120",
//     //     patient_name: "Kamala Singh",
//     //     patient_gender: "female",
//     //     patient_age: 73,
//     //     patient_phone: 8883392920,
//     //     patient_email: "kamalasingh2233@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "231",
//     //     patient_name: "Kenny Deori",
//     //     patient_gender: "male",
//     //     patient_age: 70,
//     //     patient_phone: 1192003948,
//     //     patient_email: "kennydeori22@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "120",
//     //     patient_name: "Kamala Singh",
//     //     patient_gender: "female",
//     //     patient_age: 73,
//     //     patient_phone: 8883392920,
//     //     patient_email: "kamalasingh2233@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "231",
//     //     patient_name: "Kenny Deori",
//     //     patient_gender: "male",
//     //     patient_age: 70,
//     //     patient_phone: 1192003948,
//     //     patient_email: "kennydeori22@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "120",
//     //     patient_name: "Kamala Singh",
//     //     patient_gender: "female",
//     //     patient_age: 73,
//     //     patient_phone: 8883392920,
//     //     patient_email: "kamalasingh2233@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "231",
//     //     patient_name: "Kenny Deori",
//     //     patient_gender: "male",
//     //     patient_age: 70,
//     //     patient_phone: 1192003948,
//     //     patient_email: "kennydeori22@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "120",
//     //     patient_name: "Kamala Singh",
//     //     patient_gender: "female",
//     //     patient_age: 73,
//     //     patient_phone: 8883392920,
//     //     patient_email: "kamalasingh2233@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "231",
//     //     patient_name: "Kenny Deori",
//     //     patient_gender: "male",
//     //     patient_age: 70,
//     //     patient_phone: 1192003948,
//     //     patient_email: "kennydeori22@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     // ],
//     //  [
//     //   {
//     //     patient_id: "10",
//     //     patient_name: "Bijoy madhav",
//     //     patient_gender: "male",
//     //     patient_age: 64,
//     //     patient_phone: 888339289,
//     //     patient_email: "bmadhav@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "200",
//     //     patient_name: "Shalini Singh",
//     //     patient_gender: "female",
//     //     patient_age: 79,
//     //     patient_phone: 1192008908,
//     //     patient_email: "shalinis11@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "10",
//     //     patient_name: "Bijoy madhav",
//     //     patient_gender: "male",
//     //     patient_age: 64,
//     //     patient_phone: 888339289,
//     //     patient_email: "bmadhav@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "200",
//     //     patient_name: "Shalini Singh",
//     //     patient_gender: "female",
//     //     patient_age: 79,
//     //     patient_phone: 1192008908,
//     //     patient_email: "shalinis11@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     // ],
//     // [
//     //   {
//     //     patient_id: "1011",
//     //     patient_name: "Geeta Biswas",
//     //     patient_gender: "female",
//     //     patient_age: 60,
//     //     patient_phone: 888339111,
//     //     patient_email: "gbiswas@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "2011",
//     //     patient_name: "Gangadhar Bidyadhar",
//     //     patient_gender: "male",
//     //     patient_age: 81,
//     //     patient_phone: 1192008111,
//     //     patient_email: "shaktiman90s@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     // ],
//     //  [
//     //   {
//     //     patient_id: "1101",
//     //     patient_name: "James Bond",
//     //     patient_gender: "male",
//     //     patient_age: 66,
//     //     patient_phone: 888331021,
//     //     patient_email: "bondo@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "2059",
//     //     patient_name: "Anya Frodger",
//     //     patient_gender: "female",
//     //     patient_age: 78,
//     //     patient_phone: 1192777111,
//     //     patient_email: "anyaf@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "1101",
//     //     patient_name: "James Bond",
//     //     patient_gender: "male",
//     //     patient_age: 66,
//     //     patient_phone: 888331021,
//     //     patient_email: "bondo@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "2059",
//     //     patient_name: "Anya Frodger",
//     //     patient_gender: "female",
//     //     patient_age: 78,
//     //     patient_phone: 1192777111,
//     //     patient_email: "anyaf@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     // ],
//   },
//   // },
//   {
//     id: 0,
//     doctor_name: "Dr. Kabrambam Lenglung",
//     doctor_email: "kblenglung@hmhospital.com",
//     doctor_phone: 9878911111,
//     week_one: 60,
//     week_two: 230,
//     week_three: 100,
//     week_four: 89,
//     // patient_count: {
//     //  [
//     //   {
//     //     patient_id: "120",
//     //     patient_name: "Kamala Singh",
//     //     patient_gender: "female",
//     //     patient_age: 73,
//     //     patient_phone: 8883392920,
//     //     patient_email: "kamalasingh2233@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "231",
//     //     patient_name: "Kenny Deori",
//     //     patient_gender: "male",
//     //     patient_age: 70,
//     //     patient_phone: 1192003948,
//     //     patient_email: "kennydeori22@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "120",
//     //     patient_name: "Kamala Singh",
//     //     patient_gender: "female",
//     //     patient_age: 73,
//     //     patient_phone: 8883392920,
//     //     patient_email: "kamalasingh2233@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "231",
//     //     patient_name: "Kenny Deori",
//     //     patient_gender: "male",
//     //     patient_age: 70,
//     //     patient_phone: 1192003948,
//     //     patient_email: "kennydeori22@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "120",
//     //     patient_name: "Kamala Singh",
//     //     patient_gender: "female",
//     //     patient_age: 73,
//     //     patient_phone: 8883392920,
//     //     patient_email: "kamalasingh2233@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "231",
//     //     patient_name: "Kenny Deori",
//     //     patient_gender: "male",
//     //     patient_age: 70,
//     //     patient_phone: 1192003948,
//     //     patient_email: "kennydeori22@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "120",
//     //     patient_name: "Kamala Singh",
//     //     patient_gender: "female",
//     //     patient_age: 73,
//     //     patient_phone: 8883392920,
//     //     patient_email: "kamalasingh2233@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "231",
//     //     patient_name: "Kenny Deori",
//     //     patient_gender: "male",
//     //     patient_age: 70,
//     //     patient_phone: 1192003948,
//     //     patient_email: "kennydeori22@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     // ],
//     //  [
//     //   {
//     //     patient_id: "10",
//     //     patient_name: "Bijoy madhav",
//     //     patient_gender: "male",
//     //     patient_age: 64,
//     //     patient_phone: 888339289,
//     //     patient_email: "bmadhav@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "200",
//     //     patient_name: "Shalini Singh",
//     //     patient_gender: "female",
//     //     patient_age: 79,
//     //     patient_phone: 1192008908,
//     //     patient_email: "shalinis11@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "10",
//     //     patient_name: "Bijoy madhav",
//     //     patient_gender: "male",
//     //     patient_age: 64,
//     //     patient_phone: 888339289,
//     //     patient_email: "bmadhav@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "200",
//     //     patient_name: "Shalini Singh",
//     //     patient_gender: "female",
//     //     patient_age: 79,
//     //     patient_phone: 1192008908,
//     //     patient_email: "shalinis11@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     // ],
//     // [
//     //   {
//     //     patient_id: "1011",
//     //     patient_name: "Geeta Biswas",
//     //     patient_gender: "female",
//     //     patient_age: 60,
//     //     patient_phone: 888339111,
//     //     patient_email: "gbiswas@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "2011",
//     //     patient_name: "Gangadhar Bidyadhar",
//     //     patient_gender: "male",
//     //     patient_age: 81,
//     //     patient_phone: 1192008111,
//     //     patient_email: "shaktiman90s@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     // ],
//     //  [
//     //   {
//     //     patient_id: "1101",
//     //     patient_name: "James Bond",
//     //     patient_gender: "male",
//     //     patient_age: 66,
//     //     patient_phone: 888331021,
//     //     patient_email: "bondo@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "2059",
//     //     patient_name: "Anya Frodger",
//     //     patient_gender: "female",
//     //     patient_age: 78,
//     //     patient_phone: 1192777111,
//     //     patient_email: "anyaf@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "1101",
//     //     patient_name: "James Bond",
//     //     patient_gender: "male",
//     //     patient_age: 66,
//     //     patient_phone: 888331021,
//     //     patient_email: "bondo@yahoo.com",
//     //     disease: "Malaria",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     //   {
//     //     patient_id: "2059",
//     //     patient_name: "Anya Frodger",
//     //     patient_gender: "female",
//     //     patient_age: 78,
//     //     patient_phone: 1192777111,
//     //     patient_email: "anyaf@yahoo.com",
//     //     disease: "High fever",
//     //     diagnosis: "Medical Treatment",
//     //   },
//     // ],
//     // },
//   },
// ];

// export const NIVO_BARCHART_DATA = [
//   {
//     country: "AD",
//     "hot dog": 70,
//     "hot dogColor": "hsl(335, 70%, 50%)",
//     burger: 104,
//     burgerColor: "hsl(102, 70%, 50%)",
//     sandwich: 1,
//     sandwichColor: "hsl(265, 70%, 50%)",
//     kebab: 12,
//     kebabColor: "hsl(96, 70%, 50%)",
//     fries: 151,
//     friesColor: "hsl(194, 70%, 50%)",
//     donut: 180,
//     donutColor: "hsl(294, 70%, 50%)",
//   },
//   {
//     country: "AE",
//     "hot dog": 180,
//     "hot dogColor": "hsl(335, 70%, 50%)",
//     burger: 198,
//     burgerColor: "hsl(59, 70%, 50%)",
//     sandwich: 73,
//     sandwichColor: "hsl(242, 70%, 50%)",
//     kebab: 44,
//     kebabColor: "hsl(252, 70%, 50%)",
//     fries: 57,
//     friesColor: "hsl(144, 70%, 50%)",
//     donut: 59,
//     donutColor: "hsl(193, 70%, 50%)",
//   },
//   {
//     country: "AF",
//     "hot dog": 99,
//     "hot dogColor": "hsl(254, 70%, 50%)",
//     burger: 181,
//     burgerColor: "hsl(320, 70%, 50%)",
//     sandwich: 157,
//     sandwichColor: "hsl(261, 70%, 50%)",
//     kebab: 78,
//     kebabColor: "hsl(41, 70%, 50%)",
//     fries: 168,
//     friesColor: "hsl(284, 70%, 50%)",
//     donut: 13,
//     donutColor: "hsl(241, 70%, 50%)",
//   },
//   {
//     country: "AG",
//     "hot dog": 28,
//     "hot dogColor": "hsl(52, 70%, 50%)",
//     burger: 33,
//     burgerColor: "hsl(22, 70%, 50%)",
//     sandwich: 167,
//     sandwichColor: "hsl(186, 70%, 50%)",
//     kebab: 136,
//     kebabColor: "hsl(116, 70%, 50%)",
//     fries: 158,
//     friesColor: "hsl(345, 70%, 50%)",
//     donut: 74,
//     donutColor: "hsl(344, 70%, 50%)",
//   },
//   {
//     country: "AI",
//     "hot dog": 23,
//     "hot dogColor": "hsl(41, 70%, 50%)",
//     burger: 81,
//     burgerColor: "hsl(22, 70%, 50%)",
//     sandwich: 105,
//     sandwichColor: "hsl(21, 70%, 50%)",
//     kebab: 42,
//     kebabColor: "hsl(286, 70%, 50%)",
//     fries: 26,
//     friesColor: "hsl(164, 70%, 50%)",
//     donut: 64,
//     donutColor: "hsl(123, 70%, 50%)",
//   },
//   {
//     country: "AL",
//     "hot dog": 42,
//     "hot dogColor": "hsl(75, 70%, 50%)",
//     burger: 85,
//     burgerColor: "hsl(150, 70%, 50%)",
//     sandwich: 193,
//     sandwichColor: "hsl(189, 70%, 50%)",
//     kebab: 90,
//     kebabColor: "hsl(350, 70%, 50%)",
//     fries: 21,
//     friesColor: "hsl(259, 70%, 50%)",
//     donut: 144,
//     donutColor: "hsl(216, 70%, 50%)",
//   },
//   {
//     country: "AM",
//     "hot dog": 39,
//     "hot dogColor": "hsl(177, 70%, 50%)",
//     burger: 54,
//     burgerColor: "hsl(206, 70%, 50%)",
//     sandwich: 198,
//     sandwichColor: "hsl(129, 70%, 50%)",
//     kebab: 78,
//     kebabColor: "hsl(126, 70%, 50%)",
//     fries: 101,
//     friesColor: "hsl(15, 70%, 50%)",
//     donut: 147,
//     donutColor: "hsl(216, 70%, 50%)",
//   },
// ];
